"""initial

Revision ID: 4da6e7e182b8
Revises: 4615121d99c2
Create Date: 2026-04-23 13:10:28.682858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da6e7e182b8'
down_revision = '4615121d99c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
